#!/bin/bash

#function: test_image_day
test_image_day () {
    case $1 in
         su)
           echo 1su
         ;;
         msu)
           echo 2msu
         ;;
         psu)
           echo 3psu
         ;;
         ic)
           echo 4ic
         ;;
         h)
           echo 5h
         ;;
         mc)
           echo 6mc
         ;;
         c)
           echo 7c
         ;;
         d)
           echo 8d
         ;;
         f)
           echo 9f
         ;;
         s)
           echo 10s
         ;;
         mcs)
           echo 11mcs
         ;;
         psus)
           echo 12psus
         ;;
         t)
           echo 13t
         ;;
         mct)
           echo 14mct
         ;;
         psut)
           echo 15psut
         ;;
         r)
           echo 16r
         ;;
         fl)
           echo 17fl
         ;;
         mcfl)
           echo 18mcfl
         ;;
         psfl)
           echo 19psfl
         ;;
         sn)
           echo 20sn
         ;;
         mcsn)
           echo 21mcsn
         ;;
         i)
           echo 22i
         ;;
         sl)
           echo 23sl
         ;;
         fr)
           echo 24fr
         ;;
         rsn)
           echo 25rsn
         ;;
         w)
           echo 26w
         ;;
         ho)
           echo 27ho
         ;;
         co)
           echo 28co
         ;;
         cl)
           echo 29cl 
         ;;
         mcl)
           echo 31mcl
         ;;
         pc)
           echo 32pc 
         ;;
         pcs)
           echo 36pcs
         ;;
         pct)
           echo 38pct 
         ;;
        esac
} 

#function: test_image_night
test_image_night () {
    case $1 in
		 su)
           echo 1su
         ;;
         msu)
           echo 2msu
         ;;
         psu)
           echo 3psu
         ;;
         c)
           echo 7c
         ;;
         d)
           echo 8d
         ;;
         f)
           echo 9f
         ;;
         s)
           echo 10s
         ;;
         psus)
           echo 12psus
         ;;
         t)
           echo 13t
         ;;
         psut)
           echo 15psut
         ;;
         r)
           echo 16r
         ;;
         fl)
           echo 17fl
         ;;
         psfl)
           echo 19psfl
         ;;
         sn)
           echo 20sn
         ;;
         i)
           echo 22i
         ;;
         sl)
           echo 23sl
         ;;
         fr)
           echo 24fr
         ;;
         rsn)
           echo 25rsn
         ;;
         ho)
           echo 27ho
         ;;
         co)
           echo 28co
         ;;
         cl)
           echo 29cl 
         ;;
         w)
           echo 30w
         ;;
         mcl)
           echo 31mcl
         ;;
         pc)
           echo 32pc 
         ;;
         ic)
           echo 33ic
         ;;
         h)
           echo 34h
         ;;
         mc)
           echo 35mc 
         ;;
         pcs)
           echo 36pcs
         ;;
         mcs)
           echo 37mcs 
         ;;
         pct)
           echo 38pct 
         ;;
         mct)
           echo 39mct 
         ;;
         mcfl)
           echo 40mcfl 
         ;;
         mcsn)
           echo 41mcsn 
         ;;
        esac
}

#put your Accuweather address here
#address="http://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/349727"
address="http://www.accuweather.com/en/us/state-college-pa/16801/weather-forecast/335315"
#http://www.accuweather.com/en/us/midway-oh/43151/weather-forecast/2214620"

loc_id=$(echo $address|sed 's/\/weather-forecast.*$//'|sed 's/^.*\///')
last_number=$(echo $address|sed 's/^.*\///')

kill -STOP $(pidof conky)
killall wget

radar_addr="http://climate.cod.edu/data/satellite/2km/VA_WV/current/VA_WV.rad.gif"
wget -O $HOME/.Accuweather_Conky_USA_Images/radar/VA_WV.rad.gif "$radar_addr"

curr_addr="$(echo $address|sed 's/weather-forecast.*$//')"current-weather/"$loc_id"us?day=1
wget -O $HOME/.Accuweather_Conky_USA_Images/curr_cond_raw "$curr_addr"

addr1="$(echo $address|sed 's/weather-forecast.*$//')"daily-weather-forecast/"$last_number"
wget -O $HOME/.Accuweather_Conky_USA_Images/tod_ton_raw "$addr1"

addr2="$addr1"?day=6
wget -O $HOME/.Accuweather_Conky_USA_Images/last_days_raw "$addr2"


if [[ -s $HOME/.Accuweather_Conky_USA_Images/curr_cond_raw ]]; then

	#current conditions
	sed -i '/detail-now/,/Moonrise/!d' $HOME/.Accuweather_Conky_USA_Images/curr_cond_raw
	egrep -i '"cond"|Humidity|Pressure|Cloud Cover|UV Index|Dew Point|Amount of Precipitation|Visibility|AM|PM|mph|icons-wind|detail-tab-panel|icon i-' $HOME/.Accuweather_Conky_USA_Images/curr_cond_raw > $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/^.*icon i-//g' -e 's/^.*tab-panel //g' -e 's/^.*start">//g' -e 's/^.*finish">//g' -e 's/-xl//' -e 's/\<[0-9]\>/0&/' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i 's/^.*<li>//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/<strong>//g' -e 's/<\/strong>//g' -e 's/<\/li>//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e '1d' -e 's/^.*center;">//g' -e 's/^.*icons-wind\///g' -e 's/\.gif.*$//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/^.*"cond">//g' -e 's/temp">/\n/g' -e 's/realfeel">/\n/g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/">.*$//g' -e 's/<\/span>.*$//g' -e 's/<span>.*$//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/&deg;//g' -e 's/&nbsp;//g' -e 's/RealFeel&#174; //g' -e 's/<\/div>.*$//g' -e '15d' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/Humidity: //g' -e 's/Pressure: //g' -e 's/Cloud Cover: //g' -e 's/UV Index: //g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/Dew Point: //g' -e 's/Amount of Precipitation(1 Hr): //g' -e 's/Visibility: //g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/^.*var s = //g' -e "s/^'//g" -e "s/';$//g" $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e "s/';//g" -e 's/&#176;//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	sed -i -e 's/ i-alarm.*$//g' $HOME/.Accuweather_Conky_USA_Images/curr_cond
	dos2unix $HOME/.Accuweather_Conky_USA_Images/curr_cond
	time=$(sed -n 1p $HOME/.Accuweather_Conky_USA_Images/curr_cond)
	image=$(sed -n 2p $HOME/.Accuweather_Conky_USA_Images/curr_cond)
	if [[ $time == day ]]; then
      echo "!!!!!!!!!!!!!!!!!!!!!!!!1sed -i 2s/$image/$(test_image_day $image)/"
	    sed -i 2s/$image/$(test_image_day $image)/ $HOME/.Accuweather_Conky_USA_Images/curr_cond
	elif [[ $time == night ]]; then
	    sed -i 2s/$image/$(test_image_night $image)/ $HOME/.Accuweather_Conky_USA_Images/curr_cond
	fi
	cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n 1p $HOME/.Accuweather_Conky_USA_Images/curr_cond)-s.png $HOME/.Accuweather_Conky_USA_Images/cc.png

fi


if [[ -s $HOME/.Accuweather_Conky_USA_Images/tod_ton_raw ]]; then

	#today - tonight - first 4 days
	sed -i '/current first/,/<h4>Night<\/h4>/!d' $HOME/.Accuweather_Conky_USA_Images/tod_ton_raw 
	egrep -i 'h3|"cond"|temp|icon i-|RealFeel' $HOME/.Accuweather_Conky_USA_Images/tod_ton_raw > $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e 's/^.*"#">//' -e 's/<\/a>.*$//' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	now=$(sed -n 1p $HOME/.Accuweather_Conky_USA_Images/tod_ton)
	if [[ $now == Tonight || $now == Overnight ]]; then
		sed -i '1s/night/night\n/' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	fi
	sed -i -e 's/^.*icon i-//g' -e 's/^.*"cond">//g' -e 's/\<[0-9]\>/0&/' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e '1,21s/^.*"temp">//g' -e 's/^.*"">//g' -e 's/Lo<\/span> /\n/' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e '27s/<span>&deg;/\n/' -e 's/<\/a>.*$//g' -e 's/"><.*$//g' -e 's/<\/span><\/span> <span class="realfeel">RealFeel&reg; //g' -e 's/^[ ,\t]*//g' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e 's/^ *//g' -e '22s/<span>&deg;/\n/' -e 's/<span>.*$//g' -e 's/<\/span>.*"temp">/\n/' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e 's/<\/span>.*$//g' -e 's/&deg;.*$//g' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i -e 's/Tomorrow/TOMORROW/' -e 's/Monday/MONDAY/' -e 's/Tuesday/TUESDAY/' -e 's/Wednesday/WEDNESDAY/' -e 's/Thursday/THURSDAY/' -e 's/Friday/FRIDAY/' -e 's/Saturday/SATURDAY/' -e 's/Sunday/SUNDAY/' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	sed -i 's/ i-alarm.*$//g' $HOME/.Accuweather_Conky_USA_Images/tod_ton
#  sed -i -e 's/^.*icon i-//g' $HOME/.Accuweather_Conky_USA_Images/tod_ton
	for (( i=7; i<=22; i+=5 ))
	  do
	      #image_raw=$(sed -n "${i}"p $HOME/.Accuweather_Conky_USA_Images/tod_ton)
	      #sed -i ${i}s/$image_raw/$(test_image_day $image_raw)/ $HOME/.Accuweather_Conky_USA_Images/tod_ton
	      cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n ${i}p $HOME/.Accuweather_Conky_USA_Images/tod_ton | sed 's/ //g').png $HOME/.Accuweather_Conky_USA_Images/$i.png
        #echo "cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n ${i}p $HOME/.Accuweather_Conky_USA_Images/tod_ton | sed 's/ //g').png $HOME/.Accuweather_Conky_USA_Images/$i.png"
	  done
	#image_raw=$(sed -n 26p $HOME/.Accuweather_Conky_USA_Images/tod_ton)
	#sed -i 26s/$image_raw/$(test_image_day $image_raw)/ $HOME/.Accuweather_Conky_USA_Images/tod_ton
  cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n 2p $HOME/.Accuweather_Conky_USA_Images/tod_ton | sed 's/ //g').png $HOME/.Accuweather_Conky_USA_Images/today.png
  #echo "cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n 2p $HOME/.Accuweather_Conky_USA_Images/tod_ton).png $HOME/.Accuweather_Conky_USA_Images/today.png"
	#image_raw=$(sed -n 30p $HOME/.Accuweather_Conky_USA_Images/tod_ton)
	#sed -i 30s/$image_raw/$(test_image_night $image_raw)/ $HOME/.Accuweather_Conky_USA_Images/tod_ton
	cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n 7p $HOME/.Accuweather_Conky_USA_Images/tod_ton | sed 's/ //g').png $HOME/.Accuweather_Conky_USA_Images/tonight.png

fi


if [[ -s $HOME/.Accuweather_Conky_USA_Images/last_days_raw ]]; then

	#last days
	sed -i '/day=6/,/<h4>Night<\/h4>/!d' $HOME/.Accuweather_Conky_USA_Images/last_days_raw 
	egrep -i 'h3|"cond"|temp|icon i-|RealFeel' $HOME/.Accuweather_Conky_USA_Images/last_days_raw > $HOME/.Accuweather_Conky_USA_Images/last_days
  sed -i -e 's/^.*icon i-//g' -e 's/^.*"cond">//g' -e 's/\<[0-9]\>/0&/' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i -e '1,21s/^.*"temp">//g' -e 's/^.*"#">//g' -e 's/Lo<\/span> /\n/' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i -e '27s/<span>&deg;/\n/' -e 's/<\/a>.*$//g' -e 's/"><.*$//g' -e 's/<\/span><\/span> <span class="realfeel">RealFeel&reg; //g' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i -e 's/^ *//g' -e '22s/<span>&deg;/\n/' -e 's/<span>.*$//g' -e 's/<\/span>.*"temp">/\n/' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i -e 's/<\/span>.*$//g' -e 's/&deg;.*$//g' -e 's/^[ ,\t]*//g' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i -e 's/Monday/MONDAY/' -e 's/Tuesday/TUESDAY/' -e 's/Wednesday/WEDNESDAY/' -e 's/Thursday/THURSDAY/' -e 's/Friday/FRIDAY/' -e 's/Saturday/SATURDAY/' -e 's/Sunday/SUNDAY/' $HOME/.Accuweather_Conky_USA_Images/last_days
	sed -i 's/ i-alarm.*$//g' $HOME/.Accuweather_Conky_USA_Images/last_days
	for (( i=2; i<=22; i+=5 ))
	  do
	      image_raw=$(sed -n "${i}"p $HOME/.Accuweather_Conky_USA_Images/last_days)
	      #sed -i ${i}s/$image_raw/$(test_image_day $image_raw)/ $HOME/.Accuweather_Conky_USA_Images/last_days
	      cp $HOME/.Accuweather_Conky_USA_Images/Forecast_Images/$(sed -n ${i}p $HOME/.Accuweather_Conky_USA_Images/last_days | sed 's/ //g').png $HOME/.Accuweather_Conky_USA_Images/N$i.png
	  done
	  
fi


if [[ -s $HOME/.Accuweather_Conky_USA_Images/tod_ton_raw && -s $HOME/.Accuweather_Conky_USA_Images/last_days_raw ]]; then

	#messages - messages_curr
	sed -n 27p $HOME/.Accuweather_Conky_USA_Images/tod_ton > $HOME/.Accuweather_Conky_USA_Images/messages_curr
	sed -n 31p $HOME/.Accuweather_Conky_USA_Images/tod_ton >> $HOME/.Accuweather_Conky_USA_Images/messages_curr
	sed -n 8p $HOME/.Accuweather_Conky_USA_Images/tod_ton > $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 13p $HOME/.Accuweather_Conky_USA_Images/tod_ton >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 18p $HOME/.Accuweather_Conky_USA_Images/tod_ton >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 23p $HOME/.Accuweather_Conky_USA_Images/tod_ton >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 3p $HOME/.Accuweather_Conky_USA_Images/last_days >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 8p $HOME/.Accuweather_Conky_USA_Images/last_days >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 13p $HOME/.Accuweather_Conky_USA_Images/last_days >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 18p $HOME/.Accuweather_Conky_USA_Images/last_days >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	sed -n 23p $HOME/.Accuweather_Conky_USA_Images/last_days >> $HOME/.Accuweather_Conky_USA_Images/messages_raw
	for (( i=1; i<=4; i++))
		do
			no=$(sed -n ${i}p $HOME/.Accuweather_Conky_USA_Images/messages_curr|wc -c)
			if (( no<=31 )); then
				sed -i $i"s/$/\n/" $HOME/.Accuweather_Conky_USA_Images/messages_curr
				i=$((i+1))
			elif (( no>31 )); then
				sed -i $i"s/^\(.\{31\}\)/\1\n/" $HOME/.Accuweather_Conky_USA_Images/messages_curr
				i=$((i+1))
			fi
		done
	cat $HOME/.Accuweather_Conky_USA_Images/messages_raw| cut -c -40 > $HOME/.Accuweather_Conky_USA_Images/messages
	for (( i=1; i<=18; i++))
		do
			no=$(sed -n ${i}p $HOME/.Accuweather_Conky_USA_Images/messages|wc -c)
			if (( no<=21 )); then
				sed -i $i"s/$/\n/" $HOME/.Accuweather_Conky_USA_Images/messages
				i=$((i+1))
			elif (( no>21 )); then
				sed -i $i"s/^\(.\{21\}\)/\1\n/" $HOME/.Accuweather_Conky_USA_Images/messages
				i=$((i+1))
			fi
		done
		
fi


kill -CONT $(pidof conky)




